export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST"
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS"
export const GET_REVIEWS_FAIL = "GET_REVIEWS_FAIL"

export const CREATE_REVIEWS_REQUEST = "CREATE_REVIEWS_REQUEST"
export const CREATE_REVIEWS_SUCCESS = "CREATE_REVIEWS_SUCCESS"
export const CREATE_REVIEWS_FAIL = "CREATE_REVIEWS_FAIL"

export const LIKE_REVIEW_REQUEST = "LIKE_REVIEW_REQUEST"
export const LIKE_REVIEW_SUCCESS = "LIKE_REVIEW_SUCCESS"
export const LIKE_REVIEW_FAIL = "LIKE_REVIEW_FAIL"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"

export const USER_INFO_REQUEST = "USER_INFO_REQUEST"
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS"
export const USER_INFO_FAIL = "USER_INFO_FAIL"

export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"

export const FAVOURITE_REQUEST = "FAVOURITE_REQUEST"
export const FAVOURITE_SUCCESS = "FAVOURITE_SUCCESS"

export const WATCHLIST_REQUEST = "WATCHLIST_REQUEST"
export const WATCHLIST_SUCCESS = "WATCHLIST_SUCCESS"

export const GET_FAV_REQUEST = "GET_FAV_REQUEST"
export const GET_FAV_SUCCESS = "GET_FAV_SUCCESS"

export const GET_WATCHLIST_REQUEST = "GET_WATCHLIST_REQUEST"
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS"